service: rushb

frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  region: eu-west-1
  timeout: 900
  memorySize: 2048
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:*'
            - 'sqs:*'
          Resource:
            - '*'

package:
  individually: true

functions:
  crawler:
    handler: rushb.crawler.rushb.transformer.lambda.LambdaHandler
    package:
      artifact: outputs/rushb-crawler.jar
    events:
      - schedule: cron(0 1 * * ? *)
  downloader:
    handler: rushb.downloader.rushb.transformer.lambda.DemoLinkHandler
    package:
      artifact: outputs/rushb-downloader.jar
    events:
      - sqs:
          arn: arn:aws:sqs:eu-west-1:743262912284:rushb-queue.fifo
          batchSize: 1
          functionResponseType: ReportBatchItemFailures

